https://www.kaggle.com/code/lusfernandotorres/data-science-for-financial-markets

In [ ]:
!pip install yfinance

In [2]:
!pip install quantstats

Requirement already satisfied: quantstats in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (0.0.76)
Requirement already satisfied: pandas<3.0.0,>=1.5.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (2.3.2)
Requirement already satisfied: numpy>=1.21.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (2.3.2)
Requirement already satisfied: seaborn>=0.11.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (0.13.2)
Requirement already satisfied: matplotlib>=3.3.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (3.10.6)
Requirement already satisfied: scipy>=1.7.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (1.16.1)
Requirement already satisfied: tabulate>=0.8.9 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (0.9.0)
Requirement already satisfied: yfinance>=0.2.65 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (0.2.65)
Requirement already satisfied: python-dateutil>=2.8.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (2.9.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from quantstats) (24.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from matplotlib>=3.3.0->quantstats) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from matplotlib>=3.3.0->quantstats) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from matplotlib>=3.3.0->quantstats) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from matplotlib>=3.3.0->quantstats) (1.4.9)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from matplotlib>=3.3.0->quantstats) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from matplotlib>=3.3.0->quantstats) (3.2.3)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas<3.0.0,>=1.5.0->quantstats) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas<3.0.0,>=1.5.0->quantstats) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from python-dateutil>=2.8.0->quantstats) (1.16.0)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (4.2.2)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (6.32.0)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from yfinance>=0.2.65->quantstats) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance>=0.2.65->quantstats) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance>=0.2.65->quantstats) (4.12.2)
Requirement already satisfied: cffi>=1.12.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from curl_cffi>=0.7->yfinance>=0.2.65->quantstats) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from curl_cffi>=0.7->yfinance>=0.2.65->quantstats) (2025.4.26)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.31->yfinance>=0.2.65->quantstats) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.31->yfinance>=0.2.65->quantstats) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.31->yfinance>=0.2.65->quantstats) (2.4.0)
Requirement already satisfied: pycparser in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance>=0.2.65->quantstats) (2.22)

In [3]:
!pip install pyportfolioopt

Collecting pyportfolioopt
  Downloading pyportfolioopt-1.5.6-py3-none-any.whl.metadata (22 kB)
Collecting cvxpy>=1.1.19 (from pyportfolioopt)
  Downloading cvxpy-1.7.2-cp311-cp311-macosx_10_9_universal2.whl.metadata (9.5 kB)
Collecting ecos<3.0.0,>=2.0.14 (from pyportfolioopt)
  Downloading ecos-2.0.14.tar.gz (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.4/142.4 kB 1.4 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pyportfolioopt) (2.3.2)
Requirement already satisfied: pandas>=0.19 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pyportfolioopt) (2.3.2)
Collecting plotly<6.0.0,>=5.0.0 (from pyportfolioopt)
  Using cached plotly-5.24.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.3 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pyportfolioopt) (1.16.1)
Collecting osqp>=0.6.2 (from cvxpy>=1.1.19->pyportfolioopt)
  Downloading osqp-1.0.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting clarabel>=0.5.0 (from cvxpy>=1.1.19->pyportfolioopt)
  Downloading clarabel-0.11.1-cp39-abi3-macosx_11_0_arm64.whl.metadata (4.8 kB)
Collecting scs>=3.2.4.post1 (from cvxpy>=1.1.19->pyportfolioopt)
  Downloading scs-3.2.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.19->pyportfolioopt) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.19->pyportfolioopt) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.19->pyportfolioopt) (2025.2)
Collecting tenacity>=6.2.0 (from plotly<6.0.0,>=5.0.0->pyportfolioopt)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: packaging in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt) (24.1)
Requirement already satisfied: cffi in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from clarabel>=0.5.0->cvxpy>=1.1.19->pyportfolioopt) (1.17.1)
Collecting jinja2 (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (69.5.1)
Requirement already satisfied: joblib in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt) (1.5.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.19->pyportfolioopt) (1.16.0)
Requirement already satisfied: pycparser in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from cffi->clarabel>=0.5.0->cvxpy>=1.1.19->pyportfolioopt) (2.22)
Collecting MarkupSafe>=2.0 (from jinja2->osqp>=0.6.2->cvxpy>=1.1.19->pyportfolioopt)
  Using cached MarkupSafe-3.0.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.0 kB)
Downloading pyportfolioopt-1.5.6-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 439.3 kB/s eta 0:00:000:00:01
Downloading cvxpy-1.7.2-cp311-cp311-macosx_10_9_universal2.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 3.6 MB/s eta 0:00:00a 0:00:01
Using cached plotly-5.24.1-py3-none-any.whl (19.1 MB)
Downloading clarabel-0.11.1-cp39-abi3-macosx_11_0_arm64.whl (935 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 935.1/935.1 kB 3.6 MB/s eta 0:00:00a 0:00:01
Downloading osqp-1.0.4-cp311-cp311-macosx_11_0_arm64.whl (291 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.7/291.7 kB 1.4 MB/s eta 0:00:0000:0100:01
Downloading scs-3.2.8-cp311-cp311-macosx_11_0_arm64.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 74.7 kB/s eta 0:00:00a 0:00:01
Using cached tenacity-9.1.2-py3-none-any.whl (28 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached MarkupSafe-3.0.2-cp311-cp311-macosx_11_0_arm64.whl (12 kB)
Building wheels for collected packages: ecos
  Building wheel for ecos (pyproject.toml) ... done
  Created wheel for ecos: filename=ecos-2.0.14-cp311-cp311-macosx_11_0_arm64.whl size=72759 sha256=34c168268e85241b19f18ca6ef954117b4a5ec2ae573d697895aac4219b916a0
  Stored in directory: /Users/roman/Library/Caches/pip/wheels/8d/2c/50/ee2c49471cb896af40a1109297f6d62ff1296e446f8c59c67c
Successfully built ecos
Installing collected packages: tenacity, MarkupSafe, scs, plotly, jinja2, ecos, clarabel, osqp, cvxpy, pyportfolioopt
  Attempting uninstall: plotly
    Found existing installation: plotly 6.3.0
    Uninstalling plotly-6.3.0:
      Successfully uninstalled plotly-6.3.0
Successfully installed MarkupSafe-3.0.2 clarabel-0.11.1 cvxpy-1.7.2 ecos-2.0.14 jinja2-3.1.6 osqp-1.0.4 plotly-5.24.1 pyportfolioopt-1.5.6 scs-3.2.8 tenacity-9.1.2

In [4]:
!pip install ta

Requirement already satisfied: ta in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (0.11.0)
Requirement already satisfied: numpy in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from ta) (2.3.2)
Requirement already satisfied: pandas in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from ta) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas->ta) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas->ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas->ta) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->ta) (1.16.0)

In [6]:
pip install pandas_datareader

Collecting pandas_datareader
  Using cached pandas_datareader-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Collecting lxml (from pandas_datareader)
  Downloading lxml-6.0.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.8 kB)
Requirement already satisfied: pandas>=0.23 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas_datareader) (2.3.2)
Requirement already satisfied: requests>=2.19.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas_datareader) (2.32.3)
Requirement already satisfied: numpy>=1.23.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (2025.4.26)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)
Using cached pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
Downloading lxml-6.0.1-cp311-cp311-macosx_10_9_universal2.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 540.8 kB/s eta 0:00:00a 0:00:01
Installing collected packages: lxml, pandas_datareader
Successfully installed lxml-6.0.1 pandas_datareader-0.10.0
Note: you may need to restart the kernel to use updated packages.

In [17]:
pip install optuna

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.5-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from optuna) (2.3.2)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from optuna) (24.1)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Using cached sqlalchemy-2.0.43-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.6 kB)
Collecting tqdm (from optuna)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting PyYAML (from optuna)
  Using cached PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting Mako (from alembic>=1.5.0->optuna)
  Using cached mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /opt/anaconda3/envs/algo_train/lib/python3.11/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 1.7 MB/s eta 0:00:0000:0100:01
Downloading alembic-1.16.5-py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.4/247.4 kB 4.7 MB/s eta 0:00:00a 0:00:01
Using cached sqlalchemy-2.0.43-cp311-cp311-macosx_11_0_arm64.whl (2.1 MB)
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Using cached PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl (172 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached mako-1.3.10-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, sqlalchemy, PyYAML, Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.10 PyYAML-6.0.2 alembic-1.16.5 colorlog-6.9.0 optuna-4.5.0 sqlalchemy-2.0.43 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

In [73]:
# Importing Libraries

# Data Handling
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.express as px
import plotly.graph_objs as go
import matplotlib.ticker as mtick
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)

# Financial Data Analysis
import yfinance as yf
import ta
import quantstats as qs

# Machine Learning Metrics
from sklearn.metrics import r2_score, root_mean_squared_error, confusion_matrix

# Models
from sklearn.linear_model import LinearRegression, Ridge
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.ensemble import AdaBoostRegressor, RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor

# Feature Selection
from sklearn.feature_selection import SelectKBest, f_regression

# Feature Importance
from sklearn.inspection import permutation_importance

# Hyperparameter Tuning
import optuna

# Hiding warnings 
import warnings
warnings.filterwarnings("ignore")

In [60]:
df = pd.read_csv('data/BTC-USDT.csv')
df

                date      open      high       low     close       volume
0      1502942400000   4261.48   4313.62   4261.32   4308.83    47.181009
1      1502946000000   4308.83   4328.69   4291.37   4315.32    23.234916
2      1502949600000   4330.29   4345.45   4309.37   4324.35     7.229691
3      1502953200000   4316.62   4349.99   4287.41   4349.99     4.443249
4      1502956800000   4333.32   4377.85   4333.32   4360.69     0.972807
...              ...       ...       ...       ...       ...          ...
51404  1688364000000  30673.61  30678.41  30606.00  30651.25  1036.522350
51405  1688367600000  30651.25  30759.80  30636.65  30667.19  1758.796390
51406  1688371200000  30667.19  30700.92  30599.07  30640.12  1390.909010
51407  1688374800000  30640.11  30670.00  30602.29  30610.61   833.620010
51408  1688378400000  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [61]:
df_days = pd.to_datetime(df['date'], unit='ms')
df.set_index(df_days, inplace=True)
df = df.drop(['date'], axis=1)

In [62]:
df

                         open      high       low     close       volume
date
2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                       ...       ...       ...       ...          ...
2023-07-03 06:00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
2023-07-03 07:00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
2023-07-03 08:00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
2023-07-03 09:00:00  30640.11  30670.00  30602.29  30610.61   833.620010
2023-07-03 10:00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 5 columns]

In [63]:
# Creating a Candlestick chart for Berkshire Hathaway stocks
candlestick = go.Candlestick(x=df.index,
                open=df['open'],
                high=df['high'],
                low=df['low'],
                close=df['close'],
                increasing=dict(line=dict(color='black')),
                decreasing=dict(line=dict(color='red')),
                showlegend=False)

# Layout
layout = go.Layout(
    title='Adjusted Berkshire Hathaway Class B Shares Price - 1996 to 2023',
    yaxis=dict(title='Price (USD)'),
    xaxis=dict(title='Date'),
    template = 'ggplot2',
    xaxis_rangeslider_visible=False,
    yaxis_gridcolor='white',
    xaxis_gridcolor='white',
    yaxis_tickfont=dict(color='black'),
    xaxis_tickfont=dict(color='black'),
    margin=dict(t=50,l=50,r=50,b=50)
)

fig = go.Figure(data=[candlestick], layout=layout)

# Plotting annotation
fig.add_annotation(text='Berkshire Hathaway Class B (BRK-B)',
                    font=dict(color='gray', size=30),
                    xref='paper', yref='paper',
                    x=0.5, y=0.5,
                    showarrow=False,
                    opacity=.85)

fig.show()

In [64]:
# Data Splitting
train = df[df.index.year <= 2022]
test = df[df.index.year >= 2022]

In [65]:
def feature_engineering(df):

    # Price behavior features
    df['high_low_ratio'] = df['high'] / df['low']
    df['open_adjclose_ratio'] = df['open'] / df['close']
    df['candle_to_wick_ratio'] = (df['close'] - df['open']) / (df['high'] - df['low'])
    df['candle_to_wick_ratio'] = df['candle_to_wick_ratio'].replace([np.inf, -np.inf], 0)

    # Lagged values
    df['Close_lag1'] = df['close'].shift(1)
    df['Close_lag2'] = df['close'].shift(2)
    df['Close_lag3'] = df['close'].shift(3)
    df['Close_lag5'] = df['close'].shift(5)

    # Close to lags ratio
    df['Close_lag1_ratio'] = df['close'] / df['Close_lag1']
    df['Close_lag2_ratio'] = df['close'] / df['Close_lag2']
    df['Close_lag3_ratio'] = df['close'] / df['Close_lag3'] 
    df['Close_lag5_ratio'] = df['close'] / df['Close_lag5'] 

    # Simple moving averages
    df['sma10'] = ta.trend.sma_indicator(df['close'], window = 10)
    df['sma20'] = ta.trend.sma_indicator(df['close'], window = 20)
    df['sma80'] = ta.trend.sma_indicator(df['close'], window = 80)
    df['sma100'] = ta.trend.sma_indicator(df['close'], window = 100)

    # Close to averages ratio
    df['Close_sma10_ratio'] = df['close'] / df['sma10']
    df['Close_sma20_ratio'] = df['close'] / df['sma20']
    df['Close_sma80_ratio'] = df['close'] / df['sma80']
    df['Close_sma100_ratio'] = df['close'] / df['sma100']

    # Shorter SMA to longer SMA ratio
    df['sma10_sma20_ratio'] = df['sma10'] / df['sma20']
    df['sma20_sma80_ratio'] = df['sma20'] / df['sma80']
    df['sma80_sma100_ratio'] = df['sma80'] / df['sma100']
    df['sma10_sma80_ratio'] = df['sma10'] / df['sma80']
    df['sma20_sma100_ratio'] = df['sma20'] / df['sma100']

    # Classical technical indicators
    df['rsi'] = ta.momentum.RSIIndicator(df['close']).rsi()
    df['rsi_overbought'] = (df['rsi'] >= 70).astype(int)
    df['rsi_oversold'] = (df['rsi'] <= 30).astype(int)
    df['cci'] = ta.trend.cci(df['high'], df['low'], df['close'], window=20, constant=0.015)
    df['obv'] = ta.volume.OnBalanceVolumeIndicator(close=df['close'], volume=df['volume']).on_balance_volume()
    df['obv_divergence_10_days'] = df['obv'].diff().rolling(10).sum() - df['close'].diff().rolling(10).sum()
    df['obv_divergence_20_days'] = df['obv'].diff().rolling(20).sum() - df['close'].diff().rolling(20).sum()
    
    # Daily returns in %
    df['returns_in_%'] = np.round((df['close'].pct_change()) * 100, 2)
    
    # Target variable – Daily returns shifted to a day earlier
    df['target'] = df['returns_in_%'].shift(-1)
    
    # Remove null values
    df.dropna(inplace = True)
    return df  # Return data frame with the new features above

In [66]:
train = feature_engineering(train)
test = feature_engineering(test)

In [67]:
X_train = train.drop('target', axis = 1) # Independent features X
y_train = train.target # target variable y

X_test = test.drop('target', axis = 1) # Independent features X
y_test = test.target # target variable y

In [68]:
# Initiating SelectKBest using f_regression as score function
k_best = SelectKBest(score_func = f_regression, k = 38)

# Fitting and transforming 
X_train_kbest = k_best.fit_transform(X_train, y_train)
X_test_kbest = k_best.transform(X_test)

# Obtaining indices and feature names
feature_indices = k_best.get_support(indices = True)
feature_names = X_train.columns[feature_indices]

# Obtaining p-values
p_values = k_best.pvalues_

# Creating features list
features = []

# Selecting only features with p-values below 0.2
for feature, pvalue in zip(feature_names, p_values):
    if pvalue < 0.2:
        features.append(feature)

# Printing features        
print("Selected Features:")
print(features)

Selected Features:
['open', 'high', 'low', 'close', 'high_low_ratio', 'open_adjclose_ratio', 'candle_to_wick_ratio', 'Close_lag1', 'Close_lag2', 'Close_lag3', 'Close_lag5', 'Close_lag1_ratio', 'Close_lag2_ratio', 'Close_lag3_ratio', 'Close_lag5_ratio', 'sma10', 'sma20', 'sma80', 'sma100', 'Close_sma10_ratio', 'Close_sma20_ratio', 'Close_sma80_ratio', 'Close_sma100_ratio', 'sma10_sma20_ratio', 'sma20_sma80_ratio', 'rsi_oversold', 'obv_divergence_20_days', 'returns_in_%']

In [69]:
X_train_kbest = X_train[features]
X_test_kbest = X_test[features]

In [70]:
# Best Features
regressors = [
    LinearRegression(),
    Ridge(random_state = 42),
    ExtraTreesRegressor(random_state = 42),
    GradientBoostingRegressor(random_state = 42),
    KNeighborsRegressor(),
    XGBRegressor(random_state = 42),
    LGBMRegressor(random_state = 42),
    CatBoostRegressor(random_state = 42, verbose = False),
    AdaBoostRegressor(random_state = 42),
    RandomForestRegressor(random_state = 42)
]

In [75]:
# Iterating over algorithms and printing scores
for reg in regressors:
    reg.fit(X_train_kbest, y_train)
    y_pred = reg.predict(X_test_kbest)
    r2 = r2_score(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)
    print(f'{type(reg).__name__}: R² = {r2:.2f}, Root Mean Squared Error = {rmse:.2f}')

LinearRegression: R² = -0.00, Root Mean Squared Error = 0.63
Ridge: R² = -0.00, Root Mean Squared Error = 0.63
ExtraTreesRegressor: R² = 0.76, Root Mean Squared Error = 0.31
GradientBoostingRegressor: R² = 0.01, Root Mean Squared Error = 0.63
KNeighborsRegressor: R² = 0.08, Root Mean Squared Error = 0.60
XGBRegressor: R² = 0.21, Root Mean Squared Error = 0.56
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 6887
[LightGBM] [Info] Number of data points in the train set: 46895, number of used features: 28
[LightGBM] [Info] Start training from score 0.007111
LGBMRegressor: R² = 0.09, Root Mean Squared Error = 0.60
CatBoostRegressor: R² = 0.13, Root Mean Squared Error = 0.59
AdaBoostRegressor: R² = -0.86, Root Mean Squared Error = 0.86
RandomForestRegressor: R² = 0.66, Root Mean Squared Error = 0.37